// <auto-generated />
using System;
using HiringService.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiringService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HiringDbContext))]
    partial class HiringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiringService.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EffectiveDateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date_end");

                    b.Property<DateTime>("EffectiveDateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date_start");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("HiringDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hiring_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("policy_number");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contract");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_contract_client_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_external_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_contract_is_active");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_policy_number");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("ix_contract_proposal_id");

                    b.HasIndex("ClientId", "IsActive")
                        .HasDatabaseName("ix_contract_client_id_is_active");

                    b.HasIndex("ClientId", "PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_client_id_policy_number");

                    b.HasIndex("ClientId", "ProposalId")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_client_id_proposal_id");

                    b.HasIndex("ProposalId", "IsActive")
                        .HasDatabaseName("ix_contract_proposal_id_is_active");

                    b.HasIndex("ProposalId", "PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_proposal_id_policy_number");

                    b.HasIndex("ClientId", "PolicyNumber", "IsActive")
                        .HasDatabaseName("ix_contract_client_id_policy_number_is_active");

                    b.HasIndex("ClientId", "ProposalId", "IsActive")
                        .HasDatabaseName("ix_contract_client_id_proposal_id_is_active");

                    b.HasIndex("ClientId", "ProposalId", "PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_client_id_proposal_id_policy_number");

                    b.HasIndex("ProposalId", "PolicyNumber", "IsActive")
                        .HasDatabaseName("ix_contract_proposal_id_policy_number_is_active");

                    b.HasIndex("ClientId", "ProposalId", "PolicyNumber", "IsActive")
                        .HasDatabaseName("ix_contract_client_id_proposal_id_policy_number_is_active");

                    b.ToTable("contracts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
